CREATE PROCEDURE `INSERTARDOCENTE` (DNI_DOC VARCHAR(8),
NOMBRE VARCHAR(35),
APELLLPATERNO VARCHAR(35),
APELLMATERNO VARCHAR(35),
CELULAR VARCHAR(9),
CORREO VARCHAR(45),
FOTO varbinary
)
BEGIN

DECLARE RESPUESTA VARCHAR(50);
DECLARE IDCARGO INT;

IF EXISTS (SELECT DNI_DOC FROM  DOCENTE where DNI_DOC = DNI_DOC)
	BEGIN 
	SET RESPUESTA= 'El Dni ya existe';
	select RESPUESTA as respuesta ;
	END;
ELSE IF EXISTS (SELECT * FROM DOCENTE WHERE DOCENTE.NOMBRE= NOMBRE AND DOCENTE.APELLLPATERNO = APELLLPATERNO AND DOCENTE.APELLMATERNO=APELLMATERNO)

END
